version: '3.1'
services:
   platform-changelog-ui:
     image: platform-changelog-ui
     ports:
       - "3000:3000"
   platform-changelog-api:
       image: platform-changelog-go
       ports:
           - "8000:8000"
       environment:
           DB_HOST: "localhost"
           DB_NAME: "gumbaroo"
       command:
           - /platform-changelog-api
       depends_on:
           - platform-changelog-db
   payload-tracker-db:
      image: postgres
      restart: always
      environment:
          POSTGRES_PASSWORD: crc
          POSTGRES_USER: crc
          POSTGRES_DB: gumbaroo
      ports:
          - "5432:5432"
